# Generated by Django 3.1.6 on 2022-06-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20220212_0100'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_product',
            field=models.ManyToManyField(related_name='favorite', to='catalog.Product', verbose_name='Избранное'),
        ),
    ]
