# Generated by Django 3.1.6 on 2022-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_section_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='articlemedia',
            name='image',
            field=models.ImageField(upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, upload_to='get_upload_to', verbose_name='Изображение'),
        ),
    ]
