# Generated by Django 3.1.6 on 2022-01-10 00:14

import ckeditor_uploader.fields
import config.core
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_auto_20220109_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to=config.core.get_upload_to, verbose_name='Изображение')),
                ('sort', models.IntegerField(default=0, help_text='Чем ниже число, тем приоритетнее позиция. Допустимо использование знака "минус".', verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Лицензию',
                'verbose_name_plural': 'Лицензии',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Заголовок')),
                ('slug', models.CharField(help_text='Заполняется автоматически', max_length=130, verbose_name='URL адрес')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст публикации')),
                ('image', models.ImageField(blank=True, upload_to=config.core.get_upload_to, verbose_name='Изображение')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='articlemedia',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleMedia',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
