# Generated by Django 3.1.6 on 2022-01-10 00:17

import ckeditor_uploader.fields
import config.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0006_auto_20220110_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='image_de',
            field=models.ImageField(blank=True, null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='license',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='license',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='license',
            name='title_de',
            field=models.CharField(max_length=130, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='license',
            name='title_en',
            field=models.CharField(max_length=130, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='license',
            name='title_ru',
            field=models.CharField(max_length=130, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_de',
            field=models.ImageField(blank=True, null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст публикации'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст публикации'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст публикации'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_de',
            field=models.CharField(max_length=130, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=130, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=130, null=True, verbose_name='Заголовок'),
        ),
    ]
