# Generated by Django 3.1.6 on 2022-01-09 05:21

import ckeditor_uploader.fields
import config.views
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=config.core.get_upload_to, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('sort', models.IntegerField(default=0, help_text='Чем ниже число, тем приоритетнее позиция. Допустимо использование знака "минус".', verbose_name='Сортировка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Название')),
                ('article', models.CharField(max_length=130, verbose_name='Артикул')),
                ('image', models.ImageField(upload_to=config.core.get_upload_to, verbose_name='Изображение')),
                ('descrtiption', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=config.core.get_upload_to, verbose_name='Изображение')),
                ('iframe', models.TextField(blank=True, verbose_name='Видео с YouTube')),
                ('sort', models.IntegerField(default=0, help_text='Чем ниже число, тем приоритетнее позиция. Допустимо использование знака "минус".', verbose_name='Сортировка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
                'ordering': ['sort'],
            },
        ),
    ]
