# Generated by Django 3.1.6 on 2022-01-09 05:31

import ckeditor_uploader.fields
import config.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrtiption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_de',
            field=models.ImageField(null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_en',
            field=models.ImageField(null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_ru',
            field=models.ImageField(null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_de',
            field=models.CharField(max_length=130, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=130, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=130, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='article_de',
            field=models.CharField(max_length=130, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='article_en',
            field=models.CharField(max_length=130, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='article_ru',
            field=models.CharField(max_length=130, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_de',
            field=models.ImageField(null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_en',
            field=models.ImageField(null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_ru',
            field=models.ImageField(null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_de',
            field=models.CharField(max_length=130, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=130, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=130, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='iframe_de',
            field=models.TextField(blank=True, null=True, verbose_name='Видео с YouTube'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='iframe_en',
            field=models.TextField(blank=True, null=True, verbose_name='Видео с YouTube'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='iframe_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Видео с YouTube'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='image_de',
            field=models.ImageField(blank=True, null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
    ]
