# Generated by Django 3.1.6 on 2022-01-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220109_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_de',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ru',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Цена'),
        ),
    ]
