# Generated by Django 3.1.6 on 2022-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220109_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_de',
            field=models.ImageField(null=True, upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_en',
            field=models.ImageField(null=True, upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_de',
            field=models.ImageField(null=True, upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_en',
            field=models.ImageField(null=True, upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(blank=True, upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image_de',
            field=models.ImageField(blank=True, null=True, upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='get_upload_to', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='get_upload_to', verbose_name='Изображение'),
        ),
    ]
