# Generated by Django 3.1.6 on 2022-02-10 07:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание'),
        ),
    ]
