# Generated by Django 3.1.6 on 2022-02-10 07:51

import config.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='text',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.AddField(
            model_name='productreview',
            name='advantages',
            field=models.TextField(null=True, verbose_name='Достоинства'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='disadvantages',
            field=models.TextField(null=True, verbose_name='Недостатки'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, upload_to=config.core.get_upload_to, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='name',
            field=models.CharField(max_length=130, null=True, verbose_name='Имя'),
        ),
    ]
