# Generated by Django 3.1.6 on 2022-02-11 17:11

import config.core
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productreview_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='image',
        ),
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=config.core.get_upload_to, verbose_name='Изображение')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_media', to='catalog.productreview', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
