# Generated by Django 3.1.6 on 2022-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20220211_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Сертификат'),
        ),
    ]
