# Generated by Django 3.1.6 on 2022-02-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='email',
            field=models.CharField(max_length=130, null=True, verbose_name='E-Mail'),
        ),
    ]
